"""Configuration for language checking rules and ignored words.

This module defines the default rules to disable and words to ignore
when running language quality checks on technical documents.
"""

# Default rules to disable (can be overridden via command-line arguments)
DEFAULT_DISABLED_RULES = {
    "WHITESPACE_RULE",
    "CONSECUTIVE_SPACES",
    "SENTENCE_WHITESPACE",
    "OXFORD_SPELLING_Z_NOT_S",
    "UPPERCASE_SENTENCE_START",
    "HYPHEN_TO_EN",
    "COMMA_PARENTHESIS_WHITESPACE",
    "PROBLEM_SOLVE_HYPHEN",
    "UP_TO_DATE_HYPHEN",
    "PHRASE_REPETITION",
    "IN_A_X_MANNER",
    "DECISION_MAKING",
    "EN_UNPAIRED_BRACKETS",
    "ENGLISH_WORD_REPEAT_BEGINNING_RULE",
    "DASH_RULE",
    "ADMIT_ENJOY_VB"


}


# Default words to ignore (case-sensitive; can be extended via command-line)
# The set below intentionally preserves casing because many entries are
# case-specific (e.g. organisation names, acronyms, product names).
DEFAULT_IGNORED_WORDS = {
    # --- History (Proper Noun) ---
    "Cynan",
    "Llywelyn",
    "Glyndwr",
    "Gruffudd",
    "Süleyman",
    "Sonni",
    "Jahan",
    "Askia",
    "Temujin",
    "Tyerman",
    "Babur",
    "Hardrada",
    "Cnut",
    "Nur",
    "Gruffydd",
    "Turvey",
    "Culpin",
    "Hanmer",
    "Breverton",
    "Genghis",
    "Swayer",
    "Deheubarth",
    "Songhai",
    "Harlech",
    "Khwarazmian",
    "Tondibi",
    "Western Europe",
    "Byzantine Empire",
    "Alexius",
    "Alexios",
    "Komnenos",
    "Zengi",
    "Zengid",
    "Hattin",
    "Nur ad-Din",
    "Nurad",
    "Imad al-Din",
    "Al-Din",
    "Ayyubid",
    "Ayyubids",
    "Mamluk",
    "Mamluks",
    "Baybars",
    "Baibars",
    "Akko",
    "Central Asia",
    "Songhay",
    "Djenné",
    "Djenne",
    "Djinguereber",
    "Sankoré",
    "Mansa",
    "Mansa Munsa",

    # --- History (Other) ---
    "ferch",

    # --- History (Technical Term) ---
    "motte",
    "bailey",

    # --- Geography (Initialism/Acronym) ---
    "GIS",

    # --- Geography (Technical Term) ---
    "oxbow",

    # --- Computer Science (Initialism/Acronym) ---
    "WJEC",
    "CBAC",
    "GCSE",
    "TKINTER",
    "CPU",
    "GPU",
    "RAM",
    "NIC",
    "NICs",
    "HDD",
    "SSD",
    "SD",
    "DVD",
    "PC",
    "SCSI",
    "USB",
    "HDMI",
    "RCA",
    "LAN",
    "WAN",
    "MITM",
    "SPDIF",
    "S/PDIF",
    "BPC",
    "BPP",
    "DoS",
    "DOS",
    "HUDs",
    "COUNTA",
    "IF",
    "VLOOKUP",
    "HLOOKUP",
    "COUNTIF",
    "SUMIF",
    "AVERAGEIF",
    "SORTBY",
    "UNIQUE",
    "SORT",
    "PNG",
    "JPEG",
    "SVG",
    "PDF",
    "MP4",
    "AVI",
    "MOV",
    "mp4",
    "avi",
    "mov",
    "png",
    "jpeg",
    "svg",

    # --- Computer Science (Proper Noun) ---
    "Fitzalan",
    "Llanwern",
    "Cynefin",
    "Bitesize",
    "Eduqas",
    "Elkington",

    # --- Computer Science (Technical Term) ---
    "tkinter",
    "Ethernet",
    "Wi-Fi",
    "kbps",
    "mbps",
    "gbps",
    "bps",
    "TOSLINK",
    "quad-core",
    "hexa-core",
    "octa-core",
    "deca-core",
    "bits-per-channel",
    "bit-depth",
    "multitasking",
    "multi-tasking",
    "high-speed",
    "white-hat",
    "whitehat",
    "nano",
    "cynefin",
    "cybersecurity",
    "cyber security",
    "cyberattacks",
    "cyber attacks",
    "cyberattack",
    "cyber attack",
    "multipage",
    "multi-page",
    "multi page",
    "HyperText Markup Language",
    "Hypertext Markup Language",
    "rotoscoping",
    "tweening",
    "AutoFilter",
    "flexbox",
    "Flexbox",
    "multi-player",
    "multiplayer",
    "keyframing",
    "key framing",

    # --- Computer Science (Other) ---
    "Centres",

    # --- Art and Design (Initialism/Acronym) ---
    "MoMA",
    "MOMA",
    "UWTSD",
    "NSEAD",

    # --- Art and Design (Proper Noun) ---
    "Mostyn",
    "Presteigne",
    "Lubaina",
    "Himid",
    "Yinka",
    "Shonibare",
    "Gauguin",
    "Paul Gauguin",
    "Herbert Bayer",
    "Amy Sherald",
    "Bridget Riley",
    "Banksy",
    "Salvador Dalí",
    "Dali",
    "Paul Peter Piech",

    # --- Art and Design (Technical Term) ---
    "Wayfinding",
    "mockups",
    "two-dimensional",
    "three-dimensional",
    "Powerchair",
    "Powerchair Football",
    "time-lapse",
    "storyboarding",
    "livestreamed",
    "food-related",

    # --- Dance (Proper Noun) ---
    "Rygbi",
    "Annwyl",
    "Fearghus",
    "Conchúir",
    "Conchuir",
    "ZooNation",
    "Avant-Garde",
    "Adigun",
    "Vardimon",
    "Xin",
    "Boyz",
    "Motionhouse",

    # --- Dance (Technical Term) ---
    "Chor",
    "Chór",
    "rond de jambe",
    "jambe",

    # --- Dance (Initialism/Acronym) ---
    "ABACADA",
    "CWRE",
    "AOs",
    "SAMs",

    # --- Design and Technology (Initialism/Acronym) ---
    "SAM",

    # --- Design and Technology (Technical Term) ---
    "kitronik",
    "prerelease",
    "pre-release",

    # --- Design and Technology (Proper Noun) ---
    "Kitronik",
    "Machynlleth",
    "Hwb",
    "Cynon",
    "Piech",
    "Bracewell",
    "Heatherwick",
    "Kéré",
    "Tregwynt",
    "Melin",
    "Haf",
    "Weighton",
    "Blant",
    "Byd",
    "Fairey",
    "Hickman",
    "Delita",
    "Rego",
    "Ekta",
    "Kaul",
    "Adfer",
    "Felin",
    "Fons",

    # --- Business (Initialism/Acronym) ---
    "GfT",
    "NEA",
    "NEAs",
    "IAMIS",
    "AoLE",
    "BAME",
    "Aos",
    "JCQ",
    "TNCs",

    # --- Business (Proper Noun) ---
    "Technocamps",
    "ActionAid",
    "GlobalWelsh",
    "GymShark",
    "McDonald's",
    "YouTube",
    "Merthyr Tydfil",

    # --- Business (Other) ---
    "creditworthy",
    "De Morgan's",
    "microfinance",
    "nonexamination",

    # --- Business (Technical Term) ---
    "pseudocode",
    "Raspbian",
    "Translanguage",

    # --- Core Cymraeg (Initialism/Acronym) ---
    "TGAU",

    # --- Core Cymraeg (Technical Term) ---
    "Gwneud-i-Gymru",
    "cyflymder",
    "Cyflymder",
    "Buanedd",
    "buanedd",
    "felosedd",
    "Felosedd",

    # --- Core Cymraeg (Proper Noun) ---
    "Dysgu",
    "Proffesiynol",
    "Canolfan",
    "Bedwyr",
    "Termiadur",
    "Addysg",
    "Clwb",
    "Dydd",
    "Gyda",
    "Helo",
    "Miwsig",
    "Taid",
    "Tyrd",
    "Dafydd",
    "Efa",
    "Fforestfach",
    "Ifor",
    "Nain",
    "Radyr",
    "Senedd",
    "Urdd",
    "Ymlaen",

    # --- Core Cymraeg (Other) ---
    "proffesiynol",

    # --- French (Other) ---
    "acheter",
    "adorer",
    "aimer",
    "allais",
    "avec",
    "bien",
    "Bienvenue",
    "célébrer",
    "commencer",
    "danser",
    "débarquement",
    "détester",
    "dix",
    "écouter",
    "entier",
    "épinards",
    "époque",
    "espérer",
    "essayer",
    "est-ce",
    "faire",
    "française",
    "jeunes",
    "le",
    "manger",
    "moins",
    "nager",
    "parler",
    "partager",
    "parisien",
    "préférer",
    "protéger",
    "pu",
    "puissant",
    "qu'",
    "que",
    "regarder",
    "répéter",
    "savoir",
    "se",
    "sûr",
    "tâche",
    "tien",
    "travailler",
    "visiter",
    "voyager",
    "bain",
    "marie",
    "bain-marie",
    "patissière",
    "bâton",
    "brunoise",
    "oracy",
    "Oracy",
    "timetabled",
    "Il",
    "Je",
    "Moi",
    "étranger",
    "expérience",
    "compétences",
    "informatiques",
    "employeurs",
    "emploi",
    "université",
    "Quelquefois",
    "passe-temps",

    # --- French (Proper Noun) ---
    "Cymraeg",
    "Lucien",
    "Béatrice",
    "Béa",

    # --- Physical Education and Health (Technical Term) ---
    "Boccia",
    "Camogie",
    "Goalball",
    "Trampolining",

    # --- English Language and Literature (Proper Noun) ---
    "Crossan",
    "Haddon",
    "Kay",
    "Laird",
    "Magorian",
    "Morpurgo",
    "Newbery",
    "Sherald",
    "Swindells",
    "Sirkka-Liisa",
    "Achebe",
    "Abse",
    "Acevedo",
    "Aitchison",
    "Bazin",
    "Christelle",
    "Chetty",
    "Fugard",
    "Fitzgeralds",
    "Forna",
    "Fraillon",
    "Heppenstall",
    "Kalhan",
    "Kelman",
    "Lefteri",
    "Lemn",
    "Maarten",
    "Macnamara",
    "McElhenney",
    "Meera",
    "Melhuish",
    "Mistry",
    "Monisha",
    "Nagra",
    "Parminder",
    "Pixley",
    "Reay",
    "Sathnam",
    "Syal",
    "Trivedy",
    "Troost",
    "Wilcock",
    "Yoon",
    "Zojceska",
    "Birlings",
    "Egeus",
    "Pyramus",
    "Tsotsi",
    "Copperopolis",
    "Deir Yassin",
    "Eynsford",
    "Ladbroke",
    "Malekula",
    "Nollywood",
    "Bloodaxe",
    "OpenLearn",
    "TalentLyft",
    "Transworld",
    "TriQuarterly",

    # --- English Language and Literature (Technical Term) ---
    "griots",
    "micropause",
    "obeah",
    "Sikhi",
    "translanguaging",

    # --- English Language and Literature (Other) ---
    "faery",
    "gapèd",
    "gloam",
    "lullèd",
    "shoulda",
    "wert",
    "withereth",

    # --- Drama (Proper Noun) ---
    "Adelayo",
    "Adedayo",
    "Artaud",
    "Ayling",
    "Berkoff",
    "Boal",
    "Brecht",
    "Buether",
    "Chickenshed",
    "Complicité",
    "Goch",
    "Habte",
    "Hijinx",
    "Kizer",
    "Lionboy",
    "Lolfa",
    "Macmillian",
    "Peakes",
    "Rafi",
    "RashDash",
    "Ravenhill",
    "Stanislavski",
    "Theatr",
    "Trezise",
    "Tsion",
    "Tunley",
    "Vickery",
    "Woyzeck",
    "Woza",
    "Wyddfa",
    "Zizou",

    # --- Drama (Technical Term) ---
    "Artaudian",
    "Berkoffian",
    "Brechtian",
    "arte",
    "berliner-ensemble",
    "crossfade",
    "Dramaturg",
    "freezeframes",
    "gestus",
    "gobo",
    "gobos",
    "multi-roling",
    "realia",

}